server:
  port: 8081
spring:
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://localhost:3306/cloud-user?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#  cloud:
#    nacos:
#      server-addr: localhost:8848 #nacos服务地址
#      discovery:
#        cluster-name: HZ #集群名称
#        username: nacos
#        password: nacos
mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
#eureka:
#  client:
#    service-url: #eureka 的地址信息，eureka自己也会注册到服务中心  127.0.0.1和localhost最大的区别是，127是网卡传输，受防火墙和网卡限制
#      defaultZone: http://localhost:10086/eureka

feign:
  client:
    config:
      default: #这里可以填写对应的service的名字，就缩小了范围，default默认指所有的服务
        loggerLevel: FULL